name: 🌐 Provider Request / Issue Report
description: Request a new provider or report an issue with an existing provider
labels: [provider]
body:

  - type: markdown
    attributes:
      value: |
        ## 🌐 Provider Request / Issue Report
        Use this template to either request a new provider or report an issue with an existing provider. Please provide as much detail as possible to help us understand and address your request or issue.

  - type: input
    id: request-type
    attributes:
      label: Type of Request (required)
      description: Please select whether you are requesting a new provider or reporting an issue with an existing provider.
      placeholder: "Enter 'New Provider Request' or 'Provider Issue Report'"
    validations:
      required: true

  - type: input
    id: provider-name
    attributes:
      label: Provider Name (required)
      description: Provide the name of the provider you are requesting or reporting an issue with.
      placeholder: "Example: 'Gogoganime'"
    validations:
      required: true

  - type: input
    id: provider-url
    attributes:
      label: Provider URL (required)
      description: Provide the URL of the provider you are requesting or reporting an issue with.
      placeholder: "Example: 'https://gogoanimehd.io'"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Provider Language
      description: Specify the language of the content offered by the provider.
      placeholder: "Example: 'en'"
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description (if applicable)
      description: If you are reporting an issue with an existing provider, describe the issue in detail.
      placeholder: |
        Example:
          "The provider stopped working, showing error '404'."
    validations:
      required: false

  - type: textarea
    id: other-details
    attributes:
      label: Additional Information
      description: Add any other relevant information or attachments that might help in resolving the issue or evaluating the provider.
      placeholder: "Optional: Provide any other details that might help."

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements (required)
      description: Please confirm the following:
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: If reporting an issue, I have verified the issue is related to this specific provider.
          required: true
